server:
  port: 8083

security:
  jwt:
    secret: ${JWT_SECRET:replace-with-32-byte-minimum-secret-key}

spring:
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
